version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: cani
    docker:
      - image: circleci/buildpack-deps
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: |
            IMAGE_TAG="0.0.${CIRCLE_BUILD_NUM}"
            docker build -t $IMAGE_NAME:$IMAGE_TAG .
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
    workflows:
      version: 2
      build-master:
        jobs:
          - build:
              filters:
                branches:
                  only: master
