version: 2.1
jobs:
  build_app:
    working_directory: /tmp/app/
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run:
          name: build_app
          command: |
            GOOS=linux go build ./src/main.go
            mv main cani
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - cani
      - store_artifacts:
          path: cani
  build_docker_image:
    working_directory: /tmp/app/
    environment:
      IMAGE_NAME: cani
    docker:
      - image: docker:18.06.1-ce-git
    steps:
      - checkout
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add py-pip
            pip install awscli
      - run:
          name: Build Image
          command: |
            IMAGE_TAG="0.0.${CIRCLE_BUILD_NUM}"
            docker build -t $IMAGE_NAME .
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
      - run:
          name: Push to ECR
          command: |
            REPO=${ACCOUNTID}.dkr.ecr.${REGION}.amazonaws.com
            IMAGE="${image:-$REPO/${$IMAGE_NAME}}"
            ECR_IMAGE="${REPO}/${IMAGE_NAME}"
            aws ecr get-login-password --region=${REGION} | docker login --username AWS --password-stdin ${ACCOUNTID}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_NAME}
            docker push ${ECR_IMAGE}:2020:09
            docker push ${ECR_IMAGE}:latest
            docker push $IMAGE:2020:09
            docker push $IMAGE:latest
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_app
      - build_docker_image:
          requires:
            - build_app
