version: 2
jobs:
  build:
    docker:
      - image: docker:18.06.1-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add py-pip
            pip install awscli
      - run:
          name: Build image and push
          command: |
            IMAGE_TAG="0.0.${CIRCLE_BUILD_NUM}"
            docker build -t $IMAGE_NAME:$IMAGE_TAG .
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
