version: 2.1
jobs:
  build_app:
    working_directory: /tmp/app/
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run:
          name: build_app
          command: |
            GOOS=linux go build ./src/cani.go
            mv main cani
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - cani
      - store_artifacts:
          path: cani
  build_push_docker_image:
    working_directory: /tmp/app/
    environment:
      IMAGE_NAME: cani
    docker:
      - image: docker:18.06.1-ce-git
    steps:
      - checkout
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add py-pip
            pip install awscli
      - run:
          name: Build Image
          command: |
            IMAGE_TAG="${CIRCLE_BUILD_NUM}"
            docker build -t $IMAGE_NAME .
      - run:
          name: Push to ECR
          command: |
            REPO=${ACCOUNTID}.dkr.ecr.${REGION}.amazonaws.com
            ECR_IMAGE="${REPO}/${IMAGE_NAME}"
            GIT_SHA=$(echo ${CIRCLE_SHA1} | cut -c 1-7)
            SHA1_VERSION="${GIT_SHA}"
            aws ecr get-login-password --region=${REGION} | docker login --username AWS --password-stdin ${ACCOUNTID}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_NAME}
            docker tag $IMAGE_NAME:latest ${ECR_IMAGE}
            docker tag $IMAGE_NAME:latest ${ECR_IMAGE}:${SHA1_VERSION}
            docker tag $IMAGE_NAME:latest ${ECR_IMAGE}:ver-${CIRCLE_BUILD_NUM}
            docker push ${ECR_IMAGE}:latest
            docker push ${ECR_IMAGE}:${SHA1_VERSION}
            docker push ${ECR_IMAGE}:ver-${CIRCLE_BUILD_NUM}
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_app
      - build_push_docker_image:
          requires:
            - build_app
