version: 2
jobs:
  build_app:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run:
          name: build_app
          command: |
            GOOS=linux go build ./src/main.go
            mv main cani
      - store_artifacts:
          path: cani
  build_docker_image:
    environment:
      IMAGE_NAME: cani
      VCS-TYPE: github
      USERNAME:
    docker:
      - image: docker:18.06.1-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add py-pip
            pip install awscli
      - run:
          name: Get Artifact
          command: |
            curl -H "Circle-Token: $CIRCLE_TOKEN" https://circleci.com/api/v1.1/project/${VCS-TYPE}/${CIRCLE_USERNAME}/${CIRCLE_PROJECT_REPONAME}/latest/artifacts
            pwd
            ls -alh
      - run:
          name: Build Image
          command: |
            ls -lah
            # IMAGE_TAG="0.0.${CIRCLE_BUILD_NUM}"
            # docker build -t $IMAGE_NAME:$IMAGE_TAG Dockerfile
            # docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_app
      - build_docker_image:
          requires:
            - build_app
