version: 2.1
jobs:
  build_app:
    working_directory: /app/
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run:
          name: build_app
          command: |
            GOOS=linux go build ./src/main.go
            mv main cani
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - cani
      - store_artifacts:
          path: cani
  build_docker_image:
    environment:
      IMAGE_NAME: cani
    docker:
      - image: docker:18.06.1-ce-git
    steps:
      - checkout
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add py-pip
            pip install awscli
      - run:
          name: Build Image
          command: |
            ls -lahR
            pwd
            # IMAGE_TAG="0.0.${CIRCLE_BUILD_NUM}"
            # docker build -t $IMAGE_NAME:$IMAGE_TAG Dockerfile
            # docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_app
      - build_docker_image:
          requires:
            - build_app
